### ISSUE TITLE
Spectating Hackers in Arcade.

### ISSUE THREAD

**Issue by Ruxiri** [NachtRaben/AliACraft-Issues#5]
If you are told there is a hacker in arcade and they are already in a game, you do /folo <hacker's name> but the thing is if the game is already started the players are invisible and you can't what anyone is doing

**Comment by NachtRaben** [comment]
I need you to clarify a bit, who are invisible? The people in game or the spectators? Are you asking about when the hacker is a spectator?

**Comment by FPS-Skilled** [comment]
Hi Nacht,

I've had this happen to me as well. If you do /folo to follow a player into a game, every player in that game is invisible, including the one you wanted to /folo. In order to see the players in the game, I've often had to /kill myself and then I can see the players normally again upon respawning.

**Comment by Ruxiri** [comment]
It's the players and spectators that are invisible
